[package]
name = "visuals"
version = "0.1.0"
authors = ["Rj Rybarczyk <rj@rybar.tech>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ggez = "0.5.1"
cgmath = { version = "0.17", features = ["mint"]}
gfx = "0.18"
